<x-layouts.app title="TIFAA">
    <section x-data="tifaAssistant()" x-init="init()" class="relative min-h-full overflow-hidden bg-sky-50 lg:h-full">
        <div aria-hidden="true" class="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_8%_2%,rgba(186,230,253,.78),transparent_30%),radial-gradient(circle_at_90%_8%,rgba(207,250,254,.72),transparent_27%),linear-gradient(135deg,#f4faff_0%,#eaf7fc_48%,#f7fafc_100%)]"></div>

        <div class="mx-auto grid min-h-full max-w-[1600px] gap-4 px-4 py-4 sm:px-6 lg:h-full lg:grid-cols-[.66fr_1fr] lg:gap-4 lg:px-6 lg:py-4 xl:px-8">
            <section class="flex min-h-0 flex-col rounded-[1.75rem] border border-white/80 bg-white/85 p-5 shadow-[0_18px_50px_-30px_rgba(14,116,144,.35)] backdrop-blur lg:p-6" aria-label="Asisten TIFAA">
                <div class="relative min-h-32 overflow-hidden rounded-2xl bg-gradient-to-br from-sky-100/85 via-white to-cyan-50/90 px-4 py-4 pr-28 sm:min-h-36 sm:px-5 sm:pr-32 lg:min-h-60 lg:px-6 lg:py-5 lg:pr-52 xl:min-h-[17rem] xl:pr-64">
                    <div aria-hidden="true" class="absolute -bottom-12 -left-10 size-40 rotate-12 opacity-[0.12] [background:repeating-linear-gradient(45deg,rgba(14,116,144,.8)_0_2px,transparent_2px_12px),repeating-linear-gradient(-45deg,rgba(245,158,11,.7)_0_2px,transparent_2px_16px)]"></div>
                    <div aria-hidden="true" class="absolute right-28 top-3 size-20 rotate-45 border-2 border-sky-300/50 opacity-50 lg:right-56 lg:top-5"></div>
                    <div class="relative z-10 min-w-0 max-w-[15rem] sm:max-w-[18rem] lg:max-w-[19rem]">
                        <div class="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-[11px] font-bold tracking-[.12em] text-emerald-700"><span class="size-1.5 rounded-full bg-emerald-500"></span>TIFAA SIAP MELAYANI</div>
                        <h1 class="mt-3 text-3xl font-black tracking-tight text-slate-950 xl:text-4xl">Halo, saya TIFAA.</h1>
                        <p class="mt-2 text-sm leading-6 text-slate-600">Informasi pendidikan terintegrasi Kabupaten Teluk Bintuni.</p>
                    </div>
                    <div class="pointer-events-none absolute bottom-0 right-0 z-10" data-tifaa-mascot-state="idle">
                        <img src="{{ Vite::asset('resources/images/branding/tifaa-mascot.png') }}" alt="Maskot TIFAA" class="h-32 w-auto object-contain drop-shadow-md sm:h-40 lg:h-60 xl:h-[17rem]">
                    </div>
                </div>

                <form @submit.prevent="ask()" class="mt-5" aria-label="Form pertanyaan TIFAA">
                    <label for="question" class="mb-2 block text-sm font-bold text-slate-800">Apa yang ingin Anda ketahui?</label>
                    <div class="flex gap-2">
                        <input x-ref="question" x-model="question" id="question" type="text" maxlength="1000" autocomplete="off" placeholder="Tulis pertanyaan pendidikan..." class="min-w-0 flex-1 rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-sky-500 focus:bg-white focus:ring-4 focus:ring-sky-100" :disabled="isLoading">
                        <button x-cloak x-show="voice?.recognitionSupported" type="button" @click="voice.startListening()" :aria-pressed="voice?.isListening" aria-label="Ajukan pertanyaan dengan suara" class="grid size-12 shrink-0 place-items-center rounded-2xl border border-sky-200 bg-sky-50 text-sky-700 transition hover:bg-sky-100 disabled:opacity-60" :disabled="isLoading || voice?.isListening"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10a7 7 0 0 0 14 0M12 17v5M8 22h8"/></svg></button>
                        <button type="submit" class="inline-flex h-12 shrink-0 items-center justify-center gap-2 rounded-2xl bg-sky-700 px-4 text-sm font-bold text-white shadow-lg shadow-sky-200 transition hover:bg-sky-800 disabled:bg-sky-400" :disabled="isLoading"><svg x-show="!isLoading" class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m22 2-7 20-4-9-9-4Z"/></svg><svg x-cloak x-show="isLoading" class="size-4 animate-spin" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/></svg><span class="hidden sm:inline" x-text="isLoading ? 'Memproses' : 'Tanya'">Tanya</span></button>
                    </div>
                </form>

                <div class="mt-4">
                    <div class="flex items-center justify-between gap-3"><p class="text-[11px] font-bold uppercase tracking-wider text-slate-500">Pertanyaan cepat</p><div class="flex items-center gap-1.5"><span class="text-[10px] font-semibold text-slate-400" x-text="(quickQuestionPage + 1) + ' / ' + quickQuestionPageCount()"></span><button type="button" @click="changeQuickQuestionPage(-1)" aria-label="Halaman pertanyaan sebelumnya" class="grid size-6 place-items-center rounded-lg border border-sky-100 bg-white text-sky-700 transition hover:bg-sky-50">‹</button><button type="button" @click="changeQuickQuestionPage(1)" aria-label="Halaman pertanyaan berikutnya" class="grid size-6 place-items-center rounded-lg border border-sky-100 bg-white text-sky-700 transition hover:bg-sky-50">›</button></div></div>
                    <div class="mt-2 grid grid-cols-1 gap-1.5 sm:grid-cols-2"><template x-for="item in visibleQuickQuestions()" :key="item"><button type="button" @click="ask(item)" :disabled="isLoading" class="min-w-0 rounded-xl border border-sky-100 bg-sky-50 px-3 py-2 text-left text-xs font-medium leading-4 text-sky-800 transition hover:border-sky-300 hover:bg-sky-100 disabled:opacity-60" x-text="item"></button></template></div>
                </div>

                <div class="mt-4 min-h-0 flex-1 overflow-hidden rounded-2xl border border-slate-100 bg-slate-50/80">
                    <div x-cloak x-show="voice?.isListening" class="flex h-full items-center gap-3 p-5 text-cyan-900"><span class="relative flex size-10"><span class="absolute inline-flex size-full animate-ping rounded-full bg-cyan-300 opacity-60"></span><span class="relative grid size-10 place-items-center rounded-full bg-cyan-600 text-white">♫</span></span><div><p class="font-bold">Mendengarkan...</p><p class="text-sm">Ucapkan pertanyaan Anda dengan jelas.</p><button type="button" @click="voice.cancelListening()" class="mt-2 text-xs font-bold text-cyan-700">Batalkan</button></div></div>
                    <div x-cloak x-show="isLoading" class="flex h-full items-center justify-center p-5 text-center"><div><div class="mx-auto grid size-10 place-items-center rounded-2xl bg-sky-100 text-sky-700">+</div><p class="mt-2 text-sm font-bold text-slate-900">TIFAA sedang menyiapkan jawaban</p></div></div>
                    <div x-cloak x-show="error" class="h-full overflow-y-auto p-5" role="alert"><p class="font-bold text-rose-800">TIFAA belum dapat menjawab</p><p class="mt-1 text-sm leading-6 text-rose-700" x-text="error"></p></div>
                    <div x-cloak x-show="response" class="flex h-full flex-col" aria-live="polite"><div class="bg-gradient-to-r from-sky-700 to-cyan-600 px-5 py-4 text-white"><p class="text-[11px] font-bold uppercase tracking-[.14em] text-sky-100">Jawaban TIFAA</p><p class="mt-1 text-sm font-semibold leading-6" x-text="response?.answer"></p></div><div class="min-h-0 flex-1 overflow-y-auto p-4"><div x-show="response?.visualization === 'kpi'" class="rounded-2xl bg-sky-50 p-4"><p class="text-[10px] font-bold uppercase tracking-wider text-sky-700">Hasil utama</p><p class="mt-1 text-4xl font-black text-slate-950" x-text="formattedValue()"></p></div><dl class="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-600"><div><dt>Periode</dt><dd class="font-semibold text-slate-900" x-text="response?.source?.reference_period"></dd></div><div><dt>Sumber</dt><dd class="font-semibold text-slate-900" x-text="response?.source?.dataset ?? 'Data Pendidikan Terintegrasi Teluk Bintuni'"></dd></div></dl></div><div class="border-t border-slate-100 px-4 py-3"><button type="button" @click="askAgain()" class="text-xs font-bold text-sky-700">Tanya Lagi</button></div></div>
                    <div x-show="!response && !isLoading && !error && !voice?.isListening" class="flex h-full items-center justify-center p-8 text-center"><div><div class="mx-auto grid size-11 place-items-center rounded-2xl bg-sky-100 text-xl text-sky-700">✦</div><p class="mt-3 text-sm font-bold text-slate-700">Ruang jawaban TIFAA</p><p class="mt-1 text-xs leading-5 text-slate-500">Hasil pertanyaan Anda akan tampil di sini.</p></div></div>
                </div>
                <p x-cloak x-show="voice && !voice.recognitionSupported" class="mt-2 text-xs text-slate-500">Input suara belum didukung browser ini; Anda tetap dapat mengetik.</p>
                <p x-cloak x-show="voice?.error" class="mt-2 text-xs font-medium text-rose-700" x-text="voice?.error"></p>
            </section>

            <section class="grid min-h-[23rem] gap-4 lg:min-h-0 lg:grid-cols-[minmax(0,1fr)_17rem]" aria-label="Sebaran pendidikan">
                <script id="tifa-district-summary" type="application/json">@json($districtSummary['districts'])</script>
                <div x-data="tifaMapFilters()" class="flex min-h-[20rem] min-w-0 flex-col overflow-hidden rounded-[1.75rem] border border-sky-100 bg-sky-50 shadow-[0_18px_50px_-30px_rgba(14,116,144,.25)]" aria-label="Peta Kabupaten Teluk Bintuni"><div class="shrink-0 border-b border-sky-100 bg-white/90 px-5 py-2.5"><div class="flex flex-wrap items-end justify-between gap-x-4 gap-y-2"><div><p class="text-[11px] font-bold uppercase tracking-[.15em] text-sky-700">Peta pendidikan</p><h2 class="mt-0.5 text-lg font-bold text-slate-900">Peta Sebaran Sekolah</h2></div><div class="flex flex-wrap items-center gap-2"><div class="flex flex-wrap gap-1" aria-label="Filter jenjang"><template x-for="item in [{ key: 'all', label: 'Semua' }, { key: 'KB', label: 'KB' }, { key: 'TK', label: 'TK' }, { key: 'SD', label: 'SD' }, { key: 'SMP', label: 'SMP' }, { key: 'SMA', label: 'SMA' }, { key: 'SMK', label: 'SMK' }, { key: 'other', label: 'Lainnya' }]" :key="item.key"><button type="button" @click="filters.level = item.key; apply()" :class="filters.level === item.key ? 'bg-sky-700 text-white shadow-sm' : 'bg-sky-50 text-sky-800 hover:bg-sky-100'" class="rounded-lg px-2 py-1 text-[10px] font-bold transition" x-text="item.label"></button></template></div><select x-model="filters.status" @change="apply()" class="rounded-lg border border-sky-100 bg-white px-2 py-1 text-[10px] font-semibold text-slate-700 outline-none focus:border-sky-500"><option value="all">Semua Status</option><option value="Negeri">Negeri</option><option value="Swasta">Swasta</option></select></div></div></div><div x-data="tifaEducationMap()" x-init="init()" class="tifa-map relative min-h-0 flex-1"><div x-ref="map" class="absolute inset-0" role="application" aria-label="Peta distrik Kabupaten Teluk Bintuni"></div></div></div>
                <aside x-data="tifaDistrictSummary()" x-init="init()" class="flex min-h-0 flex-col rounded-[1.75rem] border border-white/80 bg-white/85 p-5 shadow-[0_18px_50px_-30px_rgba(14,116,144,.25)]"><p class="text-[11px] font-bold uppercase tracking-[.15em] text-sky-700">Sebaran Sekolah</p><div class="flex items-baseline justify-between gap-2"><h2 class="mt-1 text-lg font-bold text-slate-900">Ringkasan Distrik</h2><span class="text-[10px] font-semibold text-slate-500" x-text="districts.length + ' distrik'">{{ count($districtSummary['districts']) }} distrik</span></div><div x-ref="districtList" class="mt-4 min-h-0 flex-1 space-y-2 overflow-y-auto pr-1"><template x-for="district in districts" :key="district.identifier"><button type="button" @click="selectDistrict(district.identifier)" :data-district-identifier="district.identifier" :class="selectedIdentifier === district.identifier ? 'border-sky-500 bg-sky-50 ring-2 ring-sky-100' : 'border-slate-100 bg-slate-50 hover:border-sky-200'" class="block w-full rounded-xl border px-3 py-2.5 text-left transition"><div class="flex items-start justify-between gap-2"><p class="min-w-0 text-xs font-bold leading-4 text-slate-800" x-text="district.name"></p><span class="shrink-0 text-lg font-black leading-4 text-sky-800" x-text="district.total_schools"></span></div><p x-show="district.has_school_data !== false" class="mt-1 text-[10px] text-slate-500"><span x-text="district.public_schools"></span> Negeri <span class="px-1 text-slate-300">•</span> <span x-text="district.private_schools"></span> Swasta</p><p x-show="district.has_school_data === false" class="mt-1 text-[10px] text-slate-500">Tidak ada sekolah pada dataset aktif</p></button></template></div><p x-cloak x-show="mapUnavailable" class="mt-3 text-[10px] leading-4 text-amber-700">Boundary distrik belum dapat dimuat.</p>@if (($districtSummary['null_or_empty_districts'] ?? 0) > 0)<p class="mt-3 text-[10px] leading-4 text-amber-700">{{ $districtSummary['null_or_empty_districts'] }} sekolah belum memiliki distrik.</p>@endif</aside>
            </section>
        </div>
    </section>
</x-layouts.app>
